describe("poste-ai.context_api", function()
  local context_api = require("poste-ai.context_api")
  local state = require("poste-ai.state")

  after_each(function()
    context_api.unregister("t1")
    context_api.unregister("t2")
    context_api.set_active(nil)
  end)

  it("registers, lists and unregisters contexts", function()
    context_api.register("t1", { system_prompt = function() return "one" end })
    context_api.register("t2", {})
    assert.are.same({ "t1", "t2" }, context_api.list())
    context_api.unregister("t1")
    assert.is_nil(context_api.get("t1"))
  end)

  it("validates registration args", function()
    assert.has_error(function() context_api.register("", {}) end)
    assert.has_error(function() context_api.register("x", nil) end)
  end)

  it("activates only known contexts", function()
    assert.is_false(context_api.set_active("ghost"))
    assert.is_nil(state.active_context)
    context_api.register("t1", {})
    assert.is_true(context_api.set_active("t1"))
    assert.are.equal("t1", state.active_context)
    context_api.set_active(nil)
    assert.is_nil(state.active_context)
  end)

  it("composes the system prompt from base + active context", function()
    context_api.register("t1", { system_prompt = function() return "DB KNOWLEDGE" end })
    local base = context_api.system_prompt()
    assert.truthy(base:find("Neovim"))
    assert.falsy(base:find("DB KNOWLEDGE"))

    context_api.set_active("t1")
    local composed = context_api.system_prompt()
    assert.truthy(composed:find("Neovim"))
    assert.truthy(composed:find("DB KNOWLEDGE"))
  end)

  it("survives a broken system_prompt implementation", function()
    context_api.register("t1", { system_prompt = function() error("boom") end })
    context_api.set_active("t1")
    assert.truthy(context_api.system_prompt():find("Neovim"))
  end)

  it("passes the chat scope snapshot to the context system_prompt", function()
    local scope = require("poste-ai.chat.scope")
    local captured
    context_api.register("t1", { system_prompt = function(sc) captured = sc return "SCOPED" end })
    context_api.set_active("t1")
    scope.set("connection", "pg")
    context_api.system_prompt()
    assert.are.same({ connection = "pg" }, captured)
    scope.set("connection", nil)
  end)
end)
