describe("poste-ai.chat.window", function()
  local window = require("poste-ai.chat.window")
  local state = require("poste-ai.state")

  after_each(function()
    window.close()
  end)

  it("opens the two-pane layout with named scratch buffers", function()
    assert.is_true(window.open())
    assert.is_true(window.is_open())
    local conv_buf = window.conversation_buf()
    local input_buf = window.input_buf()
    assert.are.equal("poste://chat", vim.api.nvim_buf_get_name(conv_buf))
    assert.are.equal("poste://chat_input", vim.api.nvim_buf_get_name(input_buf))
    assert.are.equal("poste_ai_chat", vim.api.nvim_get_option_value("filetype", { buf = conv_buf }))
    assert.are.equal("poste_ai_input", vim.api.nvim_get_option_value("filetype", { buf = input_buf }))
    assert.is_false(vim.api.nvim_get_option_value("modifiable", { buf = conv_buf }))
    assert.is_true(vim.api.nvim_get_option_value("modifiable", { buf = input_buf }))
  end)

  it("reuses buffers across close/open cycles", function()
    window.open()
    local conv_buf = window.conversation_buf()
    window.close()
    assert.is_false(window.is_open())
    assert.is_true(vim.api.nvim_buf_is_valid(conv_buf))  -- hidden, not wiped
    window.open()
    assert.are.equal(conv_buf, window.conversation_buf())
  end)

  it("round-trips input text", function()
    window.open()
    window.set_input_text("line one\nline two")
    assert.are.equal("line one\nline two", window.input_text())
    window.clear_input()
    assert.are.equal("", window.input_text())
  end)

  it("records the origin buffer when opened from a named buffer", function()
    local scratch = vim.api.nvim_create_buf(true, false)
    vim.api.nvim_buf_set_name(scratch, vim.fn.getcwd() .. "/origin_test.sql")
    vim.api.nvim_set_current_buf(scratch)
    window.open()
    assert.are.equal(scratch, state.origin_buf)
  end)

  it("installs buffer-local keymaps", function()
    window.open()
    window.focus_input(false)
    -- insert mode: Enter inserts a newline, Alt+Enter submits
    assert.is_true(vim.tbl_isempty(vim.fn.maparg("<CR>", "i", false, true)))
    local submit_i = vim.fn.maparg("<M-Cr>", "i", false, true)
    assert.is_table(submit_i)
    assert.is_truthy(submit_i.buffer)
    -- normal mode: Enter submits directly
    local submit_n = vim.fn.maparg("<CR>", "n", false, true)
    assert.is_table(submit_n)
    assert.is_truthy(submit_n.buffer)
    window.focus_chat()  -- conv keymaps resolve against the conversation buffer
    local toggle = vim.fn.maparg("R", "n", false, true)
    assert.is_table(toggle)
    assert.is_truthy(toggle.buffer)
  end)

  it("shows the chat scope at the leftmost of the context line and winbar", function()
    local scope = require("poste-ai.chat.scope")
    window.open()
    -- empty scope → "-"
    local line = vim.api.nvim_get_option_value("winbar", { win = window.input_win() })
    assert.truthy(line:find(" - ", 1, true))
    assert.truthy(vim.api.nvim_get_option_value("winbar", { win = window.conversation_win() }):find("[-]", 1, true))

    -- scoped → "pg/app"
    scope.set("connection", "pg")
    scope.set("database", "app")
    line = vim.api.nvim_get_option_value("winbar", { win = window.input_win() })
    assert.truthy(line:find(" pg/app ", 1, true))
    assert.truthy(vim.api.nvim_get_option_value("winbar", { win = window.conversation_win() }):find("[pg/app]", 1, true))
    scope.clear()
  end)

  it("marks the input pane with a colored left gutter", function()
    window.open()
    local input_win = window.input_win()
    assert.are.equal("yes", vim.api.nvim_get_option_value("signcolumn", { win = input_win }))
    local col = vim.api.nvim_get_option_value("statuscolumn", { win = input_win })
    assert.is_truthy(col:find("PosteAiInputBorder", 1, true))
    -- the conversation pane keeps its clean layout
    assert.are.equal("no", vim.api.nvim_get_option_value("signcolumn", { win = window.conversation_win() }))
  end)

  it("reports at_bottom correctly", function()
    window.open()
    local conv_win = window.conversation_win()
    assert.is_true(window.at_bottom(conv_win))  -- short buffer fits on screen
  end)
end)
